compatibility_date = "2024-08-12"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.zhjonline.org", custom_domain = true },
  { pattern = "quay.zhjonline.org", custom_domain = true },
  { pattern = "gcr.zhjonline.org", custom_domain = true },
  { pattern = "k8s-gcr.zhjonline.org", custom_domain = true },
  { pattern = "k8s.zhjonline.org", custom_domain = true },
  { pattern = "ghcr.zhjonline.org", custom_domain = true },
  { pattern = "cloudsmith.zhjonline.org", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.zhjonline.org", custom_domain = true }
